import logging
import random
import asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.types import ReplyKeyboardMarkup, KeyboardButton
from aiogram.filters import Command

# Token
TOKEN = "7984854135:AAHGIrP3G-wgrhT-IY6KaLb5NOtLeu8MGmw"
bot = Bot(token=TOKEN)
dp = Dispatcher()

# Logging sozlamalari
logging.basicConfig(level=logging.INFO)

# Tugmalar menyusi
menu_buttons = ReplyKeyboardMarkup(
    keyboard=[
        [KeyboardButton(text="📚 So‘z yodlash")],  
        [KeyboardButton(text="📖 Reading"), KeyboardButton(text="🎧 Listening")],  
        [KeyboardButton(text="📝 Mock Testlar"), KeyboardButton(text="📘 Grammatika")],  
        [KeyboardButton(text="🎙 Ovozli Aloqa")]  
    ],
    resize_keyboard=True
)

# So'zlar ro‘yxati
word_list = [
    "Proper - to‘g‘ri, mos, yaxshi",
    "Campervan - sayohat furgoni",
    "Surf - suzmoq, internetda ma’lumot qidirmoq, to‘lqin",
    "Hopefully - umid bilan, ishonamanki",
    "For a few days - bir necha kun davomida",
    "Instructor course - o‘rgatish kursi",
    "Barbecue - grilda pishirilgan taom",
    "Return - qaytmoq, qaytarib bermoq",
    "Diving - suvga sho‘ng‘ish",
    "Scuba diving - akvalang bilan suvg‘o‘ng‘ish (nafas olish apparati)",
    "Celebrate - nishonlamoq",
    "Take place - sodir bo‘lmoq",
    "Fancy dresses - bayramona liboslar",
    "Hold - uyushtirmoq, tashkil qilish",
    "Race - poyga",
    "According to - ga ko‘ra",
    "Church bell - cherkov qo‘ng‘irog‘i",
    "Pan - tova",
    "Quite well - juda yaxshi",
    "Gate - darvoza",
    "Carry - ko‘tarmoq, yurmoq",
    "Jealous - hasadgo‘y, rashkchi",
    "Hug - quchoqlamoq",
    "Cruise - dengiz sayohati",
    "Lockdown - cheklov, karantin",
    "Continent - qit’a",
    "Staff - xodim",
    "Brilliant - ajoyib, aqlli",
    "Sightseeing - diqqatga sazovor joy",
    "Disadvantage - foydasiz tomoni",
    "Passenger - yo‘lovchi",
    "Cabin - kulba, yog‘och uy",
    "Privacy - maxfiylik, tinchlik",
    "Mood - kayfiyat",
    "Athlete - atletikachi",
    "Meditating - meditatsiya",
    "Cereal - don mahsulotlari",
    "Occasionally - ba’zan",
    "Have a nap - biroz uxlab olmoq",
    "Peaceful = quiet - tinch, sokin",
    "Front yard - old hovli",
    "Back yard - orqa hovli",
    "Trampoline - batut",
    "Called - nomli, nomlangan",
    "Suburbs - shahar atrofi",
    "Imagine - tasavvur qilmoq",
    "Currently - hozirda",
    "Activity - faoliyat",
    "Post-gym - zaldan keyingi",
    "Convenient - qulay",
    "Apart from - dan tashqari",
    "Forgetful - unutib qo‘yadigan",
    "Seem - tuyilmoq",
    "Scary - qo‘rqinchli",
    "Potential risk - potensial xavf, ehtimoliy tavakkalchilik",
    "Difficult situations - qiyin vaziyatlar",
    "Have an accident - avtohalokat bo‘lmoq",
    "Strange - g‘alati, noodatiy",
    "All the time - hamma vaqt",
    "Worry - tashvish",
    "Fear - qo‘rquv",
    "Disappear - yo‘qolmoq",
    "Benefit - foyda",
    "Creature - mavjudot",
    "Rent - ijaraga olmoq",
    "Apartment - kvartira",
    "Connection - aloqa",
    "Local residents - mahalla yashovchilar",
    "Burning man - yonayotgan odam",
    "Event - voqea",
    "Desert - cho‘l",
    "Giant community - katta jamoa",
    "Statue - haykal",
    "Inclusion - qo‘shish, kiritish",
    "Responsibility - mas’uliyat",
    "Talent - qobiliyat",
    "Influencer - ta’sir qiluvchi",
    "Special dish - maxsus ovqat",
    "Over - ko‘p, oshiq",
    "The rest of us - qolganimiz",
    "Ice cream parlour - muzqaymoq do‘koni",
    "Ice cream cone - muzqaymoq noni",
    "Weird job - unusual job",
    "Mall - do‘kon",
    "Giant - huge",
    "Teen - o‘smir",
    "Several - bir nechta",
    "Roller coaster - charxpalak, karusel",
    "Decade - 10 yil",
    "Arcade - o‘yin markazi",
    "Hang out with friends - spend time with friends",
    "Provide - ta’minlamoq",
    "Source - manba",
    "Entertainment - zavq",
    "Entire - butun boshli",
    "Upcoming - kelayotgan, yaqinlashayotgan",
    "Replace - o‘rin almashmoq",
    "Pilgrim - ziyoratchi",
    "Invite - taklif qilmoq",
    "Harvest - hosil",
    "Secular holiday - rasmiy bayram (diniy emas)",
    "Represent time - vaqtni ifodalamoq",
    "Get together - to‘planmoq, yig‘ilmoq",
    "Turkey - kurka",
    "Staffing - aralashma ziravor",
    "Mashed potato - ezilgan kartoshka",
    "Pie - pirog",
    "Massive - keng ko‘lamda",
    "Band - musiqa guruh",
    "Comb - taramoq",
    "Ribbon - lenta, tasma",
    "Quality - sifat",
    "Fillet - go‘sht filesi",
    "Bowl - kosa, chinni",
    "Fever - istima",
    "Immediately - darhol",
    "Spoon - qoshiq",
    "Average - o‘rtacha",
    "Jewellery - taqinchoq",
    "Treat - muomala qilmoq",
    "Master - usta",
    "Seaside - dengiz bo‘yi",
    "Bottle - baklashka",
    "Survive - tirik qolmoq",
    "Discover - yaratmoq",
    "Contain - o‘z ichiga olmoq",
    "Damage - zarar yetkizmoq",
    "Ink - siyoh",
    "Specialist - mutaxassis",
    "Figure out - tushunmoq",
    "So-called - go‘yoki, nomiga (kinoyada)",
    "Invention - ixtiro",
    "Interrupt - xalaqt bermoq",
    "Demand - talab qilmoq",
    "Thought - g‘oya",
    "Preserve - saqlamoq",
    "Dried - quritilgan",
    "Frozen - muzlagan",
    "Tinned - konservalangan",
    "Variety - xilma-xillik",
    "Nearby - yaqin atrofda",
    "Game of darts - nishonga o‘q uzish o‘yini",
    "Soft drinks - gazli ichimliklar",
    "Beverage - ichimlik",
    "Socialize - aloqa o‘rnatmoq",
    "Ginger - zanjabil",
    "Beer - pivo",
    "Stranger - begona odam",
    "Twin - egizak",
    "Female - ayol",
    "Male - erkak",
    "Century - asr",
    "Artist - rassom",
    "Measure - o‘lchamoq",
    "Nearly - deyarli",
    "Island - orol",
    "Form - shakllanmoq",
    "Volcanic eruption - vulqon otilishi",
    "Key - muhim",
    "Landmark - diqqatga sazovor joy",
    "Wonder - mo‘jiza",
    "Tube - truba",
    "Peak - cho‘qqi",
    "Dormant volcano - faol bo‘lmagan vulqon",
    "Hope - umid qilmoq",
    "Thief - o‘g‘ri",
    "Protect - himoya qilmoq",
    "Earth - yer shari",
    "Relative - qarindosh",
    "Hurt - o‘g‘rimoq",
    "Rest - dam olmoq",
    "Care - g‘amxo‘rlik qilmoq",
    "Wag - qimirlatmoq, silkitmoq",
    "Violin - skripka",
    "Primary - asosiy",
    "Beside - yonida",
    "Timetable - jadval",
    "Environment - atrof-muhit",
    "Price - narx",
    "Grape - uzum",
    "Shark - akula",
    "Decide - qaror qabul qilmoq",
    "Solve - hal qilmoq",
    "Intriguing - qiziqarli",
    "Mystery - jumboq",
    "Turtle - toshbaqa",
    "Navigate - yo‘l topmoq",
    "Majority - asosiysi",
    "Conclude - xulosa qilmoq",
    "Plot - rejalashtirmoq",
    "Route - yo‘nalish",
    "Release - ozod qilmoq",
    "Track - izidan bormoq, kuzatmoq",
    "Approach - yaqinlashmoq",
    "Straight - tekis",
    "Indeed - haqiqatan",
    "Field - dala",
    "Rely - bog‘lanmoq, suyanmoq",
    "Shore - qirg‘oq",
    "Catch on fire - yonib ketmoq",
    "Notice - sezmoq, payqamoq",
    "Firefighter - o‘t o‘chiruvchi",
    "Blaze - yong‘in",
    "Pup water - suvni nasos bilan tortmoq",
    "Spray water - suv purkamoq",
    "Trouble - tashvish",
    "Air conditioner - konditsioner",
    "Pollution - ifloslanish",
    "Push - itarmoq",
    "Supply - ta’minot",
    "Complete - to‘liq, to‘la",
    "Promise - va’da bermoq",
    "Honor - sharaflamoq",
    "War - urush",
    "Competitive - raqobatbardosh",
    "Elite - yuqori tabaqa",
    "Military - armiya",
    "Take part in - qatnashmoq",
    "Olive - zaytun",
    "Wreath - gulchambar",
    "Strength - ustun jihat",
    "Allow - ruxsat bermoq",
    "Coincide - mos keltirmoq",
    "Religious - diniy",
    "Please - xursand qilmoq",
     "Rule - qoida",
    "Punish - jazolamoq",
    "Follow - ergashmoq",
    "Scientist - olim",
    "Reason - sabab",
    "Plane - samolyot",
    "Lawyer - advokat",
    "Government - hokimiyat",
    "Reserve - qo'riqxona",
    "Enormous - ulkan",
    "Herd - to'da",
    "Shoot - o'q otmoq",
    "Preserve - asramoq",
    "Cheetah - gepard",
    "Strict - qattiqqo'l",
    "Regret - afsuslanmoq",
    "Land - yer",
    "Shallow - sayoz",
    "Fossil - qattiq qotishma tosh",
    "Bone - suyak",
    "Gesture - imo-ishora, qiliq",
    "Express - ifodalamoq",
    "Interpret - Tarjima qilmoq",
    "Laughter - kulgu",
    "Fear - qo'rquv",
    "Pale - rangsiz, xira",
    "Suggest - taklif qilmoq",
    "Anger - jahl",
    "They scratched out their tongue - tillarini tishlab qoldilar",
    "In its turn - o'z navbatida",
    "Insulting - haqoratli, kamsituvchi",
    "Disgust - nafrat, jirkanish",
    "Contempt - mensimaslik",
    "Suffering - azoblanish, qiynalish",
    "Recognize - tanimoq, bilmoq",
    "Early humans - oldingi odamlar",
    "Gather - collect",
    "Interact - aloqa qilmoq",
    "Environment - atrof-muhit",
    "Capable - qobiliyatli, qodir",
    "Alter - change",
    "Fuel - yonilg'i",
    "Strip bark - po'stini shilmoq",
    "Increase - o'stirmoq",
    "Grazing area - o'tlash maydoni",
    "Domestication - xonakilashtirish",
    "Previously - oldin, avvallari",
    "Inedible - yeb bo'lmaydigan",
    "Process - jarayon",
    "Basic - oddiy",
    "Need - ehtiyoj",
    "Sophistication - murakkablik darajasi/taraqqiyot",
    "Pursuit - mashg'ulot, faoliyat",
    "Native language - ona tili",
    "Indeed - haqiqatan",
    "Proficiency - mukammallik",
    "Incomplete - chala",
    "Term - termin, atama",
    "Dialect - sheva",
    "Traffic - yo'l harakati",
    "Family celebration - oilaviy nishonlash",
    "Break record - rekordni buzish",
    "Set record - rekord qo'ymoq",
    "Dead - o'lgan, o'lik",
    "Alive - tirik",
    "Come true - amalga oshmoq",
    "Jumping jacks - qaychi usulda sakrash",
    "Record holder - record egasi",
    "Certain - aniq",
    "Quite rare - juda noyob",
    "Peak days - band kunlar",
    "Obviously - aniqrog'i",
    "Schedule - plan",
    "Drug - dori",
    "Frog - qurbaqa",
    "Deforestation - o'rmonlarni yo'q qilish",
    "Deadly disease - o'limga olib boradigan kasallik",
    "Mate - sherik",
    "Set up - o'rnatmoq",
    "Stream - soy",
    "Disappointed - xafa",
    "Waterfall - sharshara",
    "Return - qaytmoq",
    "Right age - mos yosh",
    "Conversationist - Ekologiyachi",
    "Factory - zavod",
    "Monster - maxluq",
    "Incredible - sezilarli",
    "Statue - haykal",
    "Exist - mavjud bo'lmoq",
    "Claw - panja",
    "Hang - ilmoq, osmoq",
    "Towards - qarab, tomonga",
    "Pick - olmoq, tanlamoq",
    "Front - oldi tomoni",
    "Backwards - orqaga qarab",
    "Protect - himoya qilmoq",
    "Filled with - bilan to'la",
    "Performance - chiqish, namoyish",
    "Burglar - bostirib kiruvchi o'g'ri",
    "Report - hisobot",
    "Wool - yung, jun",
    "Sock - paypoq",
    "Present - sovg'a",
    "Jar - banka",
    "Pleased - mamnun, xursand",
    "Bill - to'lov cheki",
    "Grass - maysa, o't",
    "Disk jockey - DJ",
    "Thin - ingichka", "Hole - chuqur",
    "Advertisement - reklama",
    "Make laugh - kuldirmoq",
    "Teenager - o’smir",
    "Sneakers - krasovka",
    "Trainers - krosovka",
    "Pair - juft",
    "Lucky - omadli",
    "Price - narx",
    "Coach - treyner, murabbiy",
    "Nasty - yoqimsiz",
    "Match - o’yin",
    "Discount - skidka",
    "Find out - bilib olmoq",
    "Award - mukofot",
    "Sense - sezgi",
    "Bomb - bomba",
    "Bark - vovullamoq",
    "Treasure - xazina",
    "Ground - yer",
    "Lookout - kuzatuv nuqtasi",
    "Bookcase - kitob javoni",
    "Carefully - ehtiyot bo‘lib/diqqat bilan",
    "Item - narsa, buyum",
    "Feather - qush pati",
    "Wing - qanot",
    "Tail - dum",
    "String - ip/asbobni tori",
    "Twig - Shoxcha",
    "Rock - qoya",
    "Stone - tosh",
    "Pebble - toshcha",
    "Bone - suyak",
    "Lizard - kaltakesak",
    "Shed - omborxona",
    "Space - bo‘sh joy",
    "Clown - masxaraboz",
    "Quarter - chorak (15 minut)",
    "Several - bir nechta",
    "Enormous - katta",
    "Life-size - haqiqiy o‘lchamdagi",
    "Crowd - to’da, olomon",
    "Inseparable - ajralmas",
    "Accompany - birga yurmoq, sherik bo‘lmok",
    "Patiently - sabr bilan",
    "Suddenly - to‘satdan",
    "Charge - baholamoq",
    "Measure - o‘lchamoq",
    "Broad - keng",
    "Narrow - tor",
    "Ordinary shop - oddiy do‘kon",
    "Skilled - mahoratli",
    "Seem - tuyilmoq",
    "Necessary - kerakli",
    "Skill - malaka, ko‘nikma",
    "Employ - ishga olmoq",
    "Customer - xaridor",
    "Employee - ishchi, xodim",
    "Classmate - sinfdosh",
    "Beat - yengmoq",
    "Complain - shikoyat qilmoq",
    "Encourage - undamoq, ruhlantirmoq",
    "Kick a ball - to‘p tepmoq",
    "Running shoes - krasovka",
    "Ache - o‘g‘rimoq",
    "Persuade - ishontirmoq",
    "Poverty - kambag‘allik",
    "Accept - qabul qilmoq",
    "Invitation - taklifnoma",
    "Circus - sirk",
    "Full-time - to‘liq stavka",
    "Prepare - tayyorlamoq",
    "Suggest - taklif qilmoq",
    "To be keen - yoqtirmoq",
    "Glad - xursand",
    "Tidy - tartibli, ozoda",
    "Feed - boqmoq, ovqat bermoq",
    "Human being - inson zoti",
    "Environment - atrof-muhit",
    "Respiratory system - nafas olish tizimi",
    "Enable - imkon bermoq",
    "Breath - nafas olmoq",
    "Oxygen - kislorod",
    "Conscious - xushyor",
    "Surface - yuza, sirt",
    "Outstanding - ajratib turadigan",
    "Mammal - sut emizuvchi",
    "Unconscious - xushini yo‘qotgan",
    "Drown - cho‘kmoq",
    "Remain - qolmoq",
    "Partially - qisman",
    "Hemisphere - hemisfera",
    "Rest - dam olmoq",
    "Completely - butunlay, mutlaqo",
    "Spread - tarqalmoq, yoyilmoq",
    "Transmit - o‘tmoq",
    "Case - holat",
    "Seafood - dengiz o‘tlari",
    "Unfortunately - baxtga qarshi, afsuski",
    "Cure - davolamoq",
    "Symptom - belgi",
    "Fever - istima",
    "Cough - yo‘taloq",
    "Sore throat - tomoq og‘rig‘i",
    "Cold - shamollash",
    "Flu - grip",
    "Sick - kasal",
    "Definite - aniq",
    "Disease - kasallik",
    "Emerge - paydo bo‘lmoq, ko‘rinmoq",
    "Reveal - ochib bermoq, oshkor qilmoq",
    "Rate - ko‘rsatkich",
    "Mild - o‘rtacha",
    "Infect - kasallik yuqmoq",
    "Severely - og‘ir tarzda, qattiq","Piece - bo'lak, qism",
    "Move - harakatlanmoq/qimirlamoq/ko'chmoq",
    "Take turn - navbat qilmoq",
    "Lose - yutkizmoq",
    "Rule - qoida",
    "Basic - asosiy",
    "Run out of time - vaqt tugamoq",
    "Blitz chess - tezkor shaxmat",
    "Fast-paced - tez suratli",
    "Pack - solmoq",
    "Bowl - kosa",
    "Plate - tarelka",
    "Pattern - namuna",
    "Daily routine - kun tartibi",
    "Sausage - kolbasa",
    "Drum - do'mbira",
    "Reddish - qizg'ish",
    "Provide - ta'minlamoq",
    "Attract - jalb qilmoq",
    "Reputation - obro'-e'tibor",
    "Almost - deyarli",
    "Beneficial - foydali",
    "Previously - oldinlari",
    "Contain - o'z ichiga olmoq",
    "Sleeplessness - uyqusizlik",
    "Unpleasant - yoqimsiz",
    "Jumpy - osonlikcha qo'rqib ketadigan",
    "Reduce - kamaytirmoq",
    "Intake - qabul qilmoq",
    "Side-effect - yon ta'siri",
    "Solve - hal qilmoq",
    "Beverage - ichimlik",
    "Remove - olib tashlamoq",
    "Claim - tasdiqlamoq",
    "Sensible - sezilarli",
    "Otherwise - aks holda",
    "Regarded as - deb hisobalanadi",
    "Creature - hayvon, mavjudot",
    "Argument - bahs-munozara",
    "In favor of - ning foydasiga/tomonida",
    "Superiority - ustunlik",
    "Satisfactory - qoniqarli",
    "Remarkable - sezilarli",
    "Forth - oldinga",
    "Frequently - tez-tez",
    "Serve - xizmat qilmoq",
    "Firsthand - to'g'ridan-to'g'ri",
    "Eye-witness - ko'z guvoh",
    "Account - hisob",
    "Official - rasmiy",
    "Residence - turar joy",
    "Relocate - qayta joylashmoq",
    "Construction - qurilish",
    "Fictional - hayoliy",
    "Extraordinary - noyob, ajoyib",
    "Abilities - qobiliyatlar",
    "Perceive - idrok etmoq, tushunmoq",
    "Skin - teri",
    "Solid - qattiq, mustahkam",
    "Locked - qulf, berkitilgan",
    "Curious - qiziquvchan",
    "Talent - qobiliyat",
    "Notice - sezmoq, payqamoq",
    "Scientific research - ilmiy tadqiqot",
    "Opaque screen - shaffof bo'lmagan ekran",
    "Blindfold - ko'zbog'lam",
    "Casual - oddiy, shunchaki",
    "Enterprising - tashabbuskor",
    "Alteration - o'zgartirish",
    "Versatile - ko'p qirrali",
    "Demand - talab",
    "Ancient - qadimgi",
    "Monument - yodgorlik",
    "Purpose - maqsada",
    "Mystery - jumboq, sir",
    "Influence - ta'sir qilmoq",
    "Raft - yog'och qayiq",
    "Stage - bosqich",
    "Settler - ko'chib brogan kishi",
    "Temple - ibodatxona",
    "Worship - ibodat qilmoq",
    "Death - o'lim",
    "Prominent - ajralib turuvchi",
    "Field - soxa",
    "Sample - namuna",
    "Analyze - analiz qilmoq",
    "Classify - tasniflamoq",
    "Bear - eslab qolmoq/chidamoq",
    "Chemical - kimyoviy",
    "Reagent - reaktiv modda",
    "Select - tanlamoq",
    "Hinder - oldini olmoq, to'smoq",
    "Detect - aniqlamoq",
    "Explore - izlamoq, tadqiqot olib bormoq",
    "Spacesuit - kosmik kiyim",
    "Stomp - qatttiq bosmoq",
    "Moon dust - oy changi",
    "Gravity - tortishish kuchi",
    "Pull - tortmoq",
    "Layer - qatlam",
    "Creepy - qo'rqinchli",
    "Island - orol",
    "Crust - qobiq",
    "Underneath - tagida, ostida",
    "Crack - yoriq",
    "Harden - qotirmoq",
    "Spill out - tashqariga oqmoq",
    "Harsh - qattiq, qalin",
    "Scary - qorqinchli",
    "Aide - yordamchi",
    "Decade - 10 yillik",
    "Impression - ta'surot",
    "Lack - oz",
    "Nutritional - ozuqaviy",
    "Prove - isbotlamoq",
    "Argue - bahslashmoq",
    "Consume - yemoq",
    "Grain - don",
    "Excessive - ko'p",
    "Founder - asoschisi",
    "Exchange - almashtirmoq",
    "Keep in touch - aloqa qilmoq",
    "Accessible - kirish mumkin bo'lgan",
    "Social network - ijtimoiy tarmoq",
    "Pod - idish",
    "Temporarily - vaqtinchalik",
    "Abundance - ko'p",
    "Form - shakllantirmoq",
    "Exceed - oshib ketmoq",
    "Click - bosish",
    "Whistle-like sound - fushtakka o'xshash tovush",
    "Vocalization - ovoz chiqarish",
    "Membership - a'zolik",
    "Rigid - qattiq, egilmas",
    "Interchange - almashinuv",
    "Establish - asos solmoq",
    "Relation - aloqa, munosabat",
    "Injured - jarohatlangan",
    "Observe - kuzatmoq",
    "Calf - buzoqcha",
    "Shallow - sayoz",
    "Strand - tola/qoldirmoq",
    "Protect - himoya qilmoq",
    "Shark - akula",
    "Doubtful - shubhali",
    "Alarm - budilnik, signal",
    "Pepper - qalampir",
    "Trick - hiyla",
    "Cultivate - parvarish qilmoq",
    "Flight - parvoz, reys",
    "Get - bormoq",
    "Bright - yorug', yorqin",
    "Expect - kutmoq, umid qilmoq",
    "Awesome - ajoyib"


]


# /start komandasi uchun handler
@dp.message(Command("start"))
async def start_command(message: types.Message):
    await message.answer("Salom! Men ingliz tilini o‘rganishda yordam beruvchi botman!", reply_markup=menu_buttons)

# 📚 So‘z yodlash tugmasi bosilganda
@dp.message(lambda message: message.text == "📚 So‘z yodlash") 
async def word_learning(message: types.Message): 
    word = random.choice(word_list)  # So‘z tanlash
    await message.answer(f"Bugungi so‘z: {word}")

# 📖 Reading tugmasi bosilganda
@dp.message(lambda message: message.text == "📖 Reading")
async def reading_materials(message: types.Message):
    await message.answer("Reading matnini bu yerdan o‘qishingiz mumkin: https://www.englishclub.com/reading/short-stories.htm")

# 🎧 Listening tugmasi bosilganda
@dp.message(lambda message: message.text == "🎧 Listening")
async def listening_materials(message: types.Message):
    await message.answer("Listening materiallari: https://elllo.org/")

# 📝 Mock Testlar tugmasi bosilganda
@dp.message(lambda message: message.text == "📝 Mock Testlar") 
async def mock_tests(message: types.Message):
    await message.answer("Mock testlar uchun resurs: https://www.ielts-exam.net/")

# 📘 Grammatika tugmasi bosilganda
@dp.message(lambda message: message.text == "📘 Grammatika")
async def grammar_books(message: types.Message): 
    await message.answer("Grammatikani o‘rganish uchun kitoblar: https://www.englishpage.com/grammar/")

# 🎙 Ovozli Aloqa tugmasi bosilganda
@dp.message(lambda message: message.text == "🎙 Ovozli Aloqa")
async def voice_chat(message: types.Message): 
    await message.answer_voice("https://www.example.com/audio/your-audio-file.ogg")



# Botni ishga tushirish uchun asinxron funksiya
async def main():
    await bot.delete_webhook(drop_pending_updates=True)  # Eski xabarlarni o‘chirish
    await dp.start_polling(bot)  # Botni ishga tushirish

# Asosiy ishga tushirish qismi
if __name__ == "__main__":
    asyncio.run(main())  # Botni boshlash

import requests

def set_webhook():
    webhook_url = "https://bot-kappa-eight.vercel.app"
    token = "7984854135:AAHGIrP3G-wgrhT-IY6KaLb5NOtLeu8MGmw"
    url = f"https://api.telegram.org/bot{token}/setWebhook?url={webhook_url}"
    response = requests.get(url)
    print(response.json())

set_webhook()
